export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';

//recommends
export const ADD_RECOMMEND = 'ADD_RECOMMEND';
export const GET_RECOMMENDS = 'GET_RECOMMENDS';
export const AWAIT_NEW_RECOMMEND_RESPONSE = 'AWAIT_NEW_RECOMMEND_RESPONSE';
export const RECEIVE_NEW_RECOMMEND_RESPONSE = 'RECEIVE_NEW_RECOMMEND_RESPONSE';
export const RECOMMEND_DISPLAY_MESSAGE = 'RECOMMEND_DISPLAY_MESSAGE';